### ISSUE TITLE
Exclude from recents

### ISSUE THREAD

**Issue by ltguillaume** [BLumia/pineapple-lock-screen#10]
I'm using this app with the option "Use application icon to lock" enabled. However, this will still show the app in Android's _Recent Apps_ dialog, which doesn't make much sense.

Would you consider adding `android:excludeFromRecents="true"` to the corresponding activity?

**Comment by BLumia** [comment]
Not quite sure but maybe replace [this line](https://github.com/BLumia/pineapple-lock-screen/blob/c9e0278257550ef653c570f06471f461c3379187/app/src/main/java/net/blumia/pineapple/lockscreen/MainActivity.kt#L37C17-L37C31) with [`finishAndRemoveTask()`](https://developer.android.com/reference/android/app/ActivityManager.AppTask#finishAndRemoveTask()) might also work?

I've heard in some device `excludeFromRecents="true"` might cause app gets killed, I currently don't have such device for testing though.

**Comment by BLumia** [comment]
Hi again!

Finally take some time to test if the previously mentioned [finishAndRemoveTask()](https://developer.android.com/reference/android/app/ActivityManager.AppTask#finishAndRemoveTask()) method is working, now I can confirm it is indeed working in all of my existing devices, which include a Pixel device with its stock ROM, some crDroid devices and LineageOS devices.

> I've heard in some device `excludeFromRecents="true"` might cause app gets killed, I currently don't have such device for testing though.

I think this is very likely still exists in some heavily modified ROMs, so I introduced a setting option to allow users opt-in this "exclude from the Recents screen" behavior.

I already pushed the change to the repo so you can try to build from source and see if that works if you want. Since there are new strings which need to be translated for that option, I'll wait a while before doing a new release. If you know another language and want to help translating, feel free to check out [Codeberg's Weblate](https://translate.codeberg.org/projects/pineapple-lock-screen/) :)

**Comment by BLumia** [comment]
Sorry for the late update, this feature is now included in the `1.4.0` tag release.

For people who are using the Google Play version, they can update the app earlier or later today. For people who are using F-droid, they might need to wait a little longer until F-droid finishes the build and ship the update to the repo. For people who prefer build from source, simply checkout 1.4.0 tag and start building will be fine :)

**Comment by BLumia** [comment]
I don't really know how the [F-droid checkupdate bot](https://gitlab.com/fdroidci) works. Ideally it should be able to detect tag update and trigger a MR at https://gitlab.com/fdroid/fdroiddata/-/merge_requests

I personally suggest using the Google Play version ([Aurora Store](https://f-droid.org/packages/com.aurora.store/) can also be used) or try build form source if you don't want to wait for F-droid update, or consider filing an issue at https://gitlab.com/fdroid/fdroiddata/-/issues to report this app is outdated.

**Comment by BLumia** [comment]
Oh sorry! A stupid mistake, I only tagged it locally but forget to push it to remote :joy:

The tag is now available here [on GitHub](https://github.com/BLumia/pineapple-lock-screen/releases/tag/1.4.0) and also [on Codeberg](https://codeberg.org/blumia/pineapple-lock-screen/releases/tag/1.4.0).

HTH
