### ISSUE TITLE
Unlocking defaults to pineapple lock screen settings

### ISSUE THREAD

**Issue by arcamagna** [BLumia/pineapple-lock-screen#3]
Is it possible to go to home screen instead of lock screen settings after unlocking?

**Comment by BLumia** [comment]
Yes, you can just swipe the lock screen app out from the recent application screen, then it will become normal.

**Comment by BLumia** [comment]
Does this solution work for you?

**Comment by BLumia** [comment]
Not sure if that solution works for you, I also adjusted some code (https://github.com/BLumia/pineapple-lock-screen/commit/b965724d418cb6bd7548845c5eb3094719e4d875) so it will be less chance to make user need to do this manually. A new release (1.1.1) should be in the next few days that you can get from Play Store. I'll close this issue for now since no further response from you...
