### ISSUE TITLE
"small" is kinda misleading with a size of 5MB

### ISSUE THREAD

**Issue by firefoxlover** [BLumia/pineapple-lock-screen#7]
May be a bit picky but a simple screen lock action widget should not take up 5MB space.

Afaik this should be a very easy command. Some launchers like Lawnchair (12MB size) include it.

[Power button tile](https://f-droid.org/packages/com.rascarlo.power.button.tile) is under 1MB in space and allows the three power button things: turn off display, show power dialog, take screenshot.

I guess the app uses a lot of common libraries for GUI, which may be wanted for this UX. But I think this could also simply be mentioned in the Apps description.

Have a nice day!

**Comment by BLumia** [comment]
> I guess the app uses a lot of common libraries for GUI...

That's just because it's based on Jetpack Compose instead of the traditional XML -based UI solution. All dependencies are from AndroidX library and nothing beyond that. Since it's open-sourced you can take a look at the Gradle file and check if there are unnecessary dependency.

> ...should not take up 5MB space

Since Jetpack Compose itself will take some space. Switching back to the traditional XML-based UI solution could save more space. But IMHO 5MB is already small enough since nowadays people already using 1TB storage android phones...

By the way, since I don't write Android application for a living (at least for now), there might be other ways to optimize the application bundle size which I don't know. If you (or any other people) know such a solution and would like to contribute, please feel free to let me know.

Thanks for the feedback again :)

**Comment by firefoxlover** [comment]
thanks, so jetpack compose it is.
